### ISSUE TITLE
Cloned working git repository with socialstream does not see jetstream components

### ISSUE THREAD

**Issue by clarkrickman2** [joelbutcher/socialstream#274] opened 2023-05-29 00:05 UTC
Am I missing something simple?  I've beat my head against this for hours.  Thank-you!

1. Create a new laravel project
2. Install and setup socialstream per instructions and verify everything is working properly
3. Commit everything to github
4. Clone repository on another developer's machine
5. Composer install && npm install && npm run dev
6. Go to login screen and see error "Unable to locate a class or view for component [authentication-card-logo]."

I understand socialstream like jetstream can only be installed on a new project.

**Environment context**
- Socialstream version: 3.9.2
- Jetstream stack: Livewire
- Laravel version:  9.52.7
- PHP version: 8.2.6

**Comment by joelbutcher** [comment] 2023-05-29 08:58
@clarkrickman2 can you confirm this only occurs when you've installed socialstream, and not when you've only installed Jetstream?

**Comment by joelbutcher** [comment] 2023-05-29 14:27
@clarkrickman2 I'm going to try and replicate the problem – can you answer the following questions, please?

> Create a new laravel project 
Where you using `composer create-project` or `laravel new` to achieve this?

> 3. Commit everything to github
> 4. Clone repository on another developer's machine

What tool were you using to interact with Git? If you were using the CLI, can you provide the exact commands you used?

**Comment by clarkrickman2** [comment] 2023-05-29 18:17
git init
git remote add origin <remote repository URL>
git add *
git commit -m "message"
git push origin main

then on dev machine

git clone <remote repository url>

**Comment by MohannadNaj** [comment] 2023-05-29 23:47
> then on dev machine
> 
> git clone ---remote repository url---

@clarkrickman2 just tried to reproduce the issue, uploaded a project to a private repo, and cloned it -in the same machine, but different directory-, I didn't encounter any issue. 

Socialstream's usage of Jetstream's components is mild and default (it doesn't touch the original Jetstream components, e.g: `authentication-card-logo`), see:

https://github.com/joelbutcher/socialstream/blob/9e3c9d068f84419066ecce5010d2f9b364392868/stubs/livewire/resources/views/auth/login.blade.php#L1-L7

Needless to say, after cloning, I had to:

``` bash
composer install
composer run post-root-package-install
composer run post-create-project-cmd
npm install
npm run dev
```

<details>
<summary>
If you run " git ls-files | grep views/components " the output should looks like:
</summary>

```
resources/views/components/action-link.blade.php
resources/views/components/action-message.blade.php
resources/views/components/action-section.blade.php
resources/views/components/application-logo.blade.php
resources/views/components/application-mark.blade.php
resources/views/components/authentication-card-logo.blade.php
resources/views/components/authentication-card.blade.php
resources/views/components/banner.blade.php
resources/views/components/button.blade.php
resources/views/components/checkbox.blade.php
resources/views/components/confirmation-modal.blade.php
resources/views/components/confirms-password.blade.php
resources/views/components/connected-account.blade.php
resources/views/components/danger-button.blade.php
resources/views/components/dialog-modal.blade.php
resources/views/components/dropdown-link.blade.php
resources/views/components/dropdown.blade.php
resources/views/components/form-section.blade.php
resources/views/components/input-error.blade.php
resources/views/components/input.blade.php
resources/views/components/label.blade.php
resources/views/components/modal.blade.php
resources/views/components/nav-link.blade.php
resources/views/components/responsive-nav-link.blade.php
resources/views/components/secondary-button.blade.php
resources/views/components/section-border.blade.php
resources/views/components/section-title.blade.php
resources/views/components/socialstream-icons/bitbucket.blade.php
resources/views/components/socialstream-icons/facebook.blade.php
resources/views/components/socialstream-icons/github.blade.php
resources/views/components/socialstream-icons/gitlab.blade.php
resources/views/components/socialstream-icons/google.blade.php
resources/views/components/socialstream-icons/linkedin.blade.php
resources/views/components/socialstream-icons/twitter.blade.php
resources/views/components/socialstream.blade.php
resources/views/components/switchable-team.blade.php
resources/views/components/validation-errors.blade.php
resources/views/components/welcome.blade.php
```
</details>

**Comment by joelbutcher** [comment] 2023-05-30 08:57
I'm closing this as I could not replicate this issue with the following steps using two laptops, one personal, one dev.

**On the personal laptop**
1. Create a new repository on GitHub `blog-test`
2. `composer create-project laravel/laravel blog`
3. `cd blog`
4. `composer require joelbutcher/socialstream:^3.9.2`
5. `php artisan socialstream:install --stack=livewire --teams --api --verification --pest`
6. `git init`
7. `git add .`
8. `git commit -m "initial commit"`
9. `git remote add origin git@github.com:joelbutcher/blog-test.git`
10. `git push -u origin main`

**On the dev laptop (w/ posgres)**

1. `cd ~/Projects`
2. `valet park`
3. `git clone git@github.com:joelbutcher/blog-test.git`
4. `cd blog-test`
5. `composer install`
6. `npm install && npm run dev`
7. `createdb laravel`
8. `cp .env.example .env`
9.  `php artisan key:generate`
10. `vim .env` set the following vars:

```diff
-APP_URL=http://localhost
+APP_URL=http://blog-test.test

-DB_CONNECTION=mysql
+DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
-DB_PORT=3306
+DB_PORT=5432
DB_DATABASE=laravel
-DB_USERNAME=root
+DB_USERNAME=postgres
DB_PASSWORD=
```

11. `php artisan migrate`
12. Open Chrome and visit `http://blog-test.test/login`:

<img width="1912" alt="screenshot" src="https://github.com/joelbutcher/socialstream/assets/7163152/13769eb9-d4e3-49e6-9b68-3a83ce0ef25f">

**Closed by joelbutcher** 2023-05-30 08:57 UTC
Labels: bug

**Comment by joelbutcher** [comment] 2023-05-30 22:07
@clarkrickman2 You're very welcome.

If you use Socialstream extensively and you'd like to show you're appreciation (and are able to!), please consider sponsoring me and my work from as little as a cup of coffee /month - it would me the world and get me a step closer to being able to work on providing high quality Laravel packages more often!
